apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    jsonData:

  - name: grafana-mqtt-datasource
    type: grafana-mqtt-datasource
    access: proxy
    isDefault: true
    readOnly: false
    editable: true
    jsonData: { "uri": "tcp://broker:1883" }
